### ISSUE TITLE
Ajouter en speaker Sophie N'Goma

### ISSUE THREAD

**Issue by jlandure** [GDG-Nantes/Devfest2022#37]
Info : https://fr.linkedin.com/in/sophie-n-goma-35824147

**Comment by SophieN44** [comment]
- Prénom / Nom : Sophie N'Goma
- Société  : Beapp
- Ville :  Nantes
- Linkedin : https://www.linkedin.com/in/sophie-n-goma-35824147/
- Bio : Après 20 ans en ecommerce et gestion de projets numériques, je me consacre désormais à déployer la démarche Numérique Responsable pour un numérique plus soutenable, plus éthique et plus humain. Animatrice pro de la Fresque du Numérique.
- Photo : ![photo Sophie](https://user-images.githubusercontent.com/113671442/190596962-a8ec5e17-04d4-4103-ab7f-5fb4e6d577e7.jpg)

**Comment by ArtyMaury** [comment]
done 🙂
