### ISSUE TITLE
Franck Pramotton - Conférencier Sobriété Numérique - Instructeur la Fresque du Numérique

### ISSUE THREAD

**Issue by fpr44** [GDG-Nantes/Devfest2022#38]
Nantes
"Repenti" d'une carrière de 30 ans chez un GAFAM, membre du Groupe de Travail Sobriété Numérique au sein de l’association «les Shifters », Instructeur et Animateur professionnel sur l'outil «La Fresque du Numérique».
Linked In : https://www.linkedin.com/in/franck-pramotton-8444151/

![2020-Franck-Id-2020-sm](https://user-images.githubusercontent.com/96847580/190524666-14443a88-bc1d-4c02-b55f-6cf15a547eb2.png)

**Comment by ArtyMaury** [comment]
Bonjour,
C'est mis à jour 🙂
