### ISSUE TITLE
Wrong label and icon on the home page's schedule button

### ISSUE THREAD

**Issue by jb-berthet** [GDG-Nantes/Devfest2022#82]
Hey, thank you for this nice event and website! 🙂

There's two times the same label on the home page but the second one redirects to the schedule, I think it is a bug (and I guess the translation is missing in locales). I can't open a PR right now but will surely so it later if you want (even if it might be too late TBH 😅). 

![Screenshot_2022-10-21-13-21-26-143_com.brave.browser.jpg](https://user-images.githubusercontent.com/23483401/197185805-1cb02c6c-72e3-4b8d-b402-a17f20e07238.jpg)

**Comment by ArtyMaury** [comment]
Hi,
Thanks for the issue, I saw the error way to late during the event, my bad.
I've changed the buttons completely since then, so all good 🙂
